framework:
    secret: '%env(APP_SECRET)%'
    session:
        enabled: true
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
    assets:
        base_urls: 'http://127.0.0.1:8000'
        packages:
            uploads:
                base_path: '/uploads'
    http_method_override: true


when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
