security:
    # Configuration du hashage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Fournisseur d’utilisateurs (base de données)
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Gestion des firewalls (zones protégées / non protégées)
    firewalls:
        # Zone publique (profiler, assets, etc.)
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Zone principale : toutes les routes authentifiées passent ici
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppCustomAuthenticator

            logout:
                path: app_logout

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800    # 7 jours
                path: /
                always_remember_me: true

    # Hiérarchie des rôles
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

    # Contrôle d’accès par route
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }       # page de login publique
        - { path: ^/register, roles: PUBLIC_ACCESS }    # page d'inscription publique
        - { path: ^/admin, roles: ROLE_ADMIN }          # accès admin uniquement
        - { path: ^/dressing, roles: ROLE_USER }
        - { path: ^/tenues, roles: ROLE_USER }
        - { path: ^/profil, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
